require('dotenv').config();
const {fetch, Headers } = require('undici');
const express = require('express');
const axios = require('axios');
const SpotifyWebApi = require('spotify-web-api-node');
const { GoogleGenAI } = require('@google/genai');
const app = express();
const port = process.env.PORT || 3001;
const cors = require('cors');
const path = require('path');

global.fetch = fetch;
global.Headers = Headers;

app.use(cors());
app.use(express.json());

app.use(express.static(path.join(__dirname, 'public')));

app.get('/', (req, res) => {
    res.send('Backend is working');
});

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const spotifyApi = new SpotifyWebApi({
    clientId: process.env.SPOTIFY_CLIENT_ID,
    clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
    redirectUri: process.env.SPOTIFY_REDIRECT_URI,
});


app.get('/auth/spotify', (req, res) => {
    const scopes = ['user-library-read', 'playlist-modify-public'];
    console.log('Using redirect URI:', spotifyApi.getRedirectURI());
    const authUrl = spotifyApi.createAuthorizeURL(scopes);
    res.redirect(authUrl);
})

app.get('/callback', async (req, res) => {
    const { code } = req.query;

    if(!code) {
        return res.status(400).send('Error: No code received');
    }

    try {
        const data = await spotifyApi.authorizationCodeGrant(code);
        const accessToken = data.body['access_token'];
        const refreshToken = data.body['refresh_token'];
        
        spotifyApi.setAccessToken(accessToken);
        spotifyApi.setRefreshToken(refreshToken);

        res.redirect(`https://playlist-generator-olive.vercel.app/#access_token=${accessToken}`)
    } catch (err) {
        console.error('Error during Spotify callback', err);
        res.status(500).send('Error during authentication');
    }
});

async function getPlaylistPrompt(prompt) {
    try {
        const result = await ai.models.generateContent ({
            model: "gemini-2.0-flash",
            contents : prompt
        });

        const text = result?.text;

            if(!text) {
                throw new Error('No text generated by Gemini.');
            }

        console.log('Gemini API Response', text);
        return text;
    } catch (error) {
        console.error('Error fetching data from Gemini API: ', error.message);
        throw error;
    }
}

async function searchSpotifyTracks(keywords) {
    await authenticateSpotify();
    const tracks = await spotifyApi.searchTracks(keywords, { limit: 10 });
    return tracks.body.tracks.items.map(track => ({ 
        name: track.name,
        artist: track.artists[0].name,
        url: track.external_urls.spotify,
    }))
};

app.post('/generate-playlist', async (req, res) => {
    const{prompt} = req.body;

    if (!prompt) {
        return res.status(400).send('Missing required fields.');
    }
    
    console.log('Received request body:', req.body);

    if (!prompt) {
        return res.status(400).send('Error: Prompt is missing');
    }
    try {
        const geminiResponse = await getPlaylistPrompt(prompt);
        res.json({playlist: geminiResponse});
    } catch (error) {
        console.error('Error generating playlist:', error)
        res.status(500).send('Error generating playlist');
    }
});

app.listen(port, () => {
    console.log(`Server runnong on port ${port}`)
})

app.post('/export-playlist', async (req, res) => {
    const { playlistName, tracks, accessToken } = req.body;

    if (!playlistName || !tracks || !accessToken) {
        return res.status(400).send('Missing required fields.');
    }

    try {

        const spotifyApi = new SpotifyWebApi();
        spotifyApi.setAccessToken(accessToken);

        const me = await spotifyApi.getMe();
        const userId = me.body.id;

        console.log('Exporting playlist for user:', userId);

        const newPlaylist = await spotifyApi.createPlaylist(playlistName, { public: true });
        
        if(!newPlaylist || !newPlaylist.body || !newPlaylist.body.id) {
            throw new Error('Failed to create playlist.');
        }
        const playlistId = newPlaylist.body.id;
        
        const trackUris = [];

        for (const track of tracks) {
            const searchResult = await spotifyApi.searchTracks(`${track.name} ${track.artist}`, { limit: 1 });
            const foundTrack = searchResult.body.tracks.items[0];
            if (foundTrack) {
                trackUris.push(foundTrack.uri);
                }
        }

        console.log('Found', trackUris.length, 'track URIs.');

        if (trackUris.length > 0) {
            await spotifyApi.addTracksToPlaylist(playlistId, trackUris);
        } else {
            return res.status(400).json({error: 'No valid tracks found to create playlist.'})
        }
        
        console.log('Playlist successfully created!');
        return res.json({playlistUrl: `https://open.spotify.com/playlist/${playlistId}`});
    } catch (error) {
        console.error('Error exporting playlisst: ', error);
        res.status(500).send('Error exporting playlist.');
    }
});


console.log('Spotify Client ID:', process.env.SPOTIFY_CLIENT_ID);  // Debug log
